services:
  - type: web
    name: decibel-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: decibel-db
          property: connectionString
      - key: CLOUDINARY_URL
        sync: false # you’ll set it in the dashboard
databases:
  - name: decibel-db
    databaseName: decibel
    user: decibel_user
